name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: podman run -it -v ./site:/src -p 127.0.0.1:1313:1313 --rm ghcr.io/hugomods/hugo hugo server --disableFastRender -D
